apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-tru-autoscaler
  namespace: temporal-autoscaler
  labels:
    app.kubernetes.io/name: temporal-tru-autoscaler
    app.kubernetes.io/component: controller
