//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalTRUAutoscaler) DeepCopyInto(out *TemporalTRUAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalTRUAutoscaler.
func (in *TemporalTRUAutoscaler) DeepCopy() *TemporalTRUAutoscaler {
	if in == nil {
		return nil
	}
	out := new(TemporalTRUAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalTRUAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalTRUAutoscalerList) DeepCopyInto(out *TemporalTRUAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TemporalTRUAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalTRUAutoscalerList.
func (in *TemporalTRUAutoscalerList) DeepCopy() *TemporalTRUAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(TemporalTRUAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalTRUAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalTRUAutoscalerSpec) DeepCopyInto(out *TemporalTRUAutoscalerSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	out.ScaleUpCooldown = in.ScaleUpCooldown
	out.ScaleDownCooldown = in.ScaleDownCooldown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalTRUAutoscalerSpec.
func (in *TemporalTRUAutoscalerSpec) DeepCopy() *TemporalTRUAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(TemporalTRUAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalTRUAutoscalerStatus) DeepCopyInto(out *TemporalTRUAutoscalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastScaleDirection != nil {
		in, out := &in.LastScaleDirection, &out.LastScaleDirection
		*out = new(ScaleDirection)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalTRUAutoscalerStatus.
func (in *TemporalTRUAutoscalerStatus) DeepCopy() *TemporalTRUAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(TemporalTRUAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}
