{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal-tru-autoscaler.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "temporal-tru-autoscaler.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "temporal-tru-autoscaler.selectorLabels" . | nindent 4 }}
{{- end }}
